# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 271e4cc9ffbf4d487f16e63943b14aec3b0d1624b85c7890627842384637b4301fcda2f7cf507598109e814e63e02ae5f994b7c74edd992cb1a3f02636871b37

test:
  secret_key_base: 18e4ac6d94675143d1a7f3e1de574eef25305cf214bd4eb84f4b79343ddcb5e4227d0b963dff1459aa777163649a379a8b20bf076cd2bb52156e3a6640754741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
